### ISSUE TITLE
react-markdown with remark-math and rehype-katex can't correctly parse formula contents of type \[\]

### ISSUE THREAD

**Issue by hejuting** [remarkjs/react-markdown#875] opened 2024-12-04 03:49 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

all

### Steps to reproduce

``` react
import ReactMarkdown from "react-markdown";
import "katex/dist/katex.min.css";
import RemarkMath from "remark-math";
import RemarkBreaks from "remark-breaks";
import RehypeKatex from "rehype-katex";
import RemarkGfm from "remark-gfm";
import RehypeHighlight from "rehype-highlight";
import rehypeRaw from "rehype-raw";

function TestMarkdown(){

  const content = "\\[\n" +
      "a=b^2" +
      "\n\\]"

  return <ReactMarkdown
      remarkPlugins={[RemarkMath, RemarkGfm, RemarkBreaks]}
      rehypePlugins={[
        RehypeKatex,
        [
          RehypeHighlight,
          {
            detect: false,
            ignoreMissing: true,
          },
        ],
        rehypeRaw,
      ]}
      skipHtml={false}
  >
    {content}
  </ReactMarkdown>
}


```

### Actual behavior

![image](https://github.com/user-attachments/assets/facdc0ec-5085-42e1-8c39-76fabcf7992a)

### Expected behavior

![image](https://github.com/user-attachments/assets/35424804-4938-4fee-8a86-4f7133cf4fb2)

### Runtime

"react-markdown": "9.0.1", "rehype-highlight": "7.0.1", "rehype-katex": "7.0.1", "rehype-raw": "7.0.0", "remark-breaks": "3.0.2", "remark-gfm": "4.0.0", "remark-math": "6.0.0",

**Comment by ChristianMurphy** [comment] 2024-12-04 04:04
Please see the remark math documentation, it uses $ and $$ for math

**Comment by ChristianMurphy** [comment] 2024-12-04 04:05
Duplicate of https://github.com/remarkjs/remark-math/issues/100

**Closed by ChristianMurphy** 2024-12-04 04:05 UTC
Labels: 🤞 phase/open
