### ISSUE TITLE
Add support for defining custom React key generator

### ISSUE THREAD

**Issue by dang1412** [remarkjs/react-markdown#466] opened 2020-09-24 12:13 UTC
Hi react-markdown maintainers, 
I want an option which I can optionally choose how to set the key for the rendered React element.

Background: As you can see in the demo page https://rexxars.github.io/react-markdown/, every time we enter a new line all the components below it get re-rendered because they get a new key which cause React unnecessarily re-render them while they are not changed at all (Dom rendering is costly).

## Current
```js
const key = [node.type, pos.line, pos.column, index].join('-')
```

## Propose
```js
const key = typeof options.keyGenerator === 'function ' ? options.keyGenerator(node, pos, index) : [node.type, pos.line, pos.column, index].join('-')
```

This option will allow user to be able to choose when a React element should be re-rendered effectively. Thank you!

**Comment by ChristianMurphy** [comment] 2020-10-08 14:31
@dang1412 this sounds like an [XY problem](https://en.wikipedia.org/wiki/XY_problem).
Could you give some context on what you are trying to do?

**Comment by ChristianMurphy** [comment] 2020-10-08 19:27
potentially related https://github.com/remarkjs/react-markdown/issues/289 and https://github.com/remarkjs/react-markdown/issues/459

**Comment by ChristianMurphy** [comment] 2020-10-08 20:02
If there is a generic way to improve performance through better keys it would be welcome.
I'm cautious about being overly optimistic that stable identifiers would perform better than letting react rerender.
The first approach that comes to mind that would work generally would be generating a [merkle tree](https://en.wikipedia.org/wiki/Merkle_tree) with a fast hash function (murmur, blake2, etc), which would bubble changes up.
But it's questionable if hashing would be faster than just re-rendering.

React rerenders are fast enough in many cases, that being said if you have some traces and a specific suggestion on where to improve keying I'd be interested to see/hear it.

**Comment by ChristianMurphy** [comment] 2020-10-19 19:25
@dang1412 friendly reminder that this needs some more context/info.

**Comment by dang1412** [comment] 2020-10-20 14:00
@ChristianMurphy Thank you for your response. Please let me think more about this and get back later. Your suggestion really sounds interesting.

**Comment by wooorm** [comment] 2020-11-19 15:59
@dang1412 And, have you thought about it? 😉 Do those alternatives work?

**Comment by ChristianMurphy** [comment] 2020-12-08 23:51
Without a specific need or direction, this isn't actionable. Closing it out for now.
If a specific need or direction comes up, this can be revisited.

**Closed by ChristianMurphy** 2020-12-08 23:51 UTC
Labels: 🧘 status/waiting

**Comment by baumandm** [comment] 2021-04-02 14:26
I'm running into the same issue with a very specific use case:  I've used the [remark-directive](https://github.com/remarkjs/remark-directive) plugin to create a [Vega-Lite](https://vega.github.io/vega-lite/) directive, so users can directly embed a visualization spec in a Markdown document and have it rendered on-the-fly.  Vega-Lite can take ~1 second to compile and render the visualization, especially if it's loading external data.

This is acceptable when doing a one-shot render of the document.  However, in the editor with a live preview, it doesn't work well.  Editing other parts of the document forces the entire document to be re-rendered, and the lag on the Vega-Lite visualizations causes them to flicker in and out and re-flow the document.

Everywhere else the React re-render is fast enough that it doesn't cause any visual horror, but this is particularly jarring.

What if there was a way to turn on a stable key per node?  Either let me calculate `node.key` manually in my plugin, or provide an internal hashing function that can be enabled per-node with `node.useStableKey = true` or similar.

```js
const key = node.key ?? [node.type, pos.line, pos.column, index].join('-')
```

This avoids the issue of hashing everything unnecessarily, while providing a solution for actually slow components.

**Comment by ChristianMurphy** [comment] 2021-04-02 14:32
@baumandm to render a custom node type, you need a custom renderer, correct?
The custom renderer can set a `key` attribute hashing any combination of attributes you want.

**Comment by baumandm** [comment] 2021-04-02 15:45
Yes, but that doesn't prevent my custom renderer from being unmounted and recreated, which is the actual issue.  If it was just re-rendering the same component it wouldn't cause any issues.

I tried monkey patching the `ast-to-react.js` code as I suggested above, but that also doesn't fix it, so perhaps it's not just a key issue.

I guess you were right about this being an XY problem, so if you want I'd be happy to create a new issue to track this.

**Comment by ChristianMurphy** [comment] 2021-04-02 15:53
> I guess you were right about this being an XY problem, so if you want I'd be happy to create a new issue to track this.

It sounds like it may be.
For questions/discussions https://github.com/remarkjs/remark/discussions is a good avenue to continue the conversation.
If you've encountered a specific bug or have a new feature request an new issue could work.

**Comment by baumandm** [comment] 2021-04-02 20:28
After some more debugging I found the root cause of my issues: I was recalculating the `renderers` option instead of caching it, and that caused all the rendered components to be unmounted and recreated with every change.

With that fixed, I was able to set `node.key` from within my custom plugin, and it works as expected.
