### ISSUE TITLE
feature-request: Support passing mdast as source

### ISSUE THREAD

**Issue by hayaokimura** [remarkjs/react-markdown#528] opened 2021-01-03 08:12 UTC
### Subject of the feature
I want exec remark plugin on server side and pass mdast to ReactMarkdown.

I'm developing a blog with Next.js and using ReactMarkdown to displaying articles. I want create blog card from URL with get OGP Metadata. like this.

<img src="https://user-images.githubusercontent.com/8371588/103474005-8e489080-4de2-11eb-88fe-31cfad445d10.png" width="300" />

Since I want to get the OGP Metadata at build time, the process needs to be on the server side. 
Specifically, I want to do it in `getStaticProps` of Next.js. 

I wrote a remark plugin to get OGP Metadata, but the current ReactMarkdown can only receive the original Markdown, so I can't run the remark plugin on the server side.

I want to be able to generate a Markdown AST on the server and pass the AST to ReactMarkdown.

I thought that this function would be very convenient because it would allow various remark plugins to be executed on the server side.

### Expected behavior

I want to be able to pass mdast to ReactMarkdown. Like this,
```jsx
# when passing Markdown string
<ReactMarkdown children={mdSource} />
# when passing mdast object
<ReactMarkdown children={astSource} isSourceAst />
```

When `isSourceAst = true`, if you allow AST object to be passed, you will be able to run the remark plugin on the backend.

I think this feature can be achieved by changing this line in react-markdown.js as follows:
https://github.com/remarkjs/react-markdown/blob/634f88d610c3beb39411db5c928d2cfff440f9ff/src/react-markdown.js#L32-L35 

```js

  // eslint-disable-next-line no-sync
  let tree = isSourceAst ? processor.runSync(src) : processor.runSync(processor.parse(src))

```

I would appreciate your comments and suggestions. thank you.

**Comment by wooorm** [comment] 2021-01-04 09:33
We recently had this discussion: https://github.com/remarkjs/react-markdown/pull/512. I’ll close this because it seems like a duplicate to me. Feel free to comment below if you think it’s different.

Duplicate of #512

**Closed by wooorm** 2021-01-04 09:33 UTC
Labels: 🔍 status/open, 🦋 type/enhancement
