### ISSUE TITLE
How to use the property `renderers`?

### ISSUE THREAD

**Issue by codler** [remarkjs/react-markdown#678] opened 2022-03-29 13:34 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Where can I find documentation on `renderers`?

### Solution

Where can I find documentation on `renderers`?

### Alternatives

Where can I find documentation on `renderers`?

**Comment by ChristianMurphy** [comment] 2022-03-29 13:40
Duplicate of https://github.com/remarkjs/remark/discussions/977
Discussions is the appropriate place for questions

**Closed by ChristianMurphy** 2022-03-29 13:40 UTC
Labels: 🙋 no/question, 👎 phase/no
