### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by devgalib** [remarkjs/react-markdown#756] opened 2023-07-26 15:03 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

tried

### Link to runnable example

tried

### Steps to reproduce

```JSX
import path from 'path';
import { promises as fs } from 'fs';
import { ReactMarkdown } from 'react-markdown/lib/react-markdown';
import {Prism as SyntaxHighlighter} from 'react-syntax-highlighter'
import { dark } from 'react-syntax-highlighter/dist/esm/styles/prism'


export default async function Home () {
  const markdownFile = path.join(process.cwd());
  const fileContent = await fs.readFile(markdownFile + '/markdown.md', 'utf8')
  console.log()
  return (
    <div className='prose'>
      <ReactMarkdown
    // eslint-disable-next-line react/no-children-prop
    children={fileContent}
    components={{
      code({node, inline, className, children, ...props}) {
        const match = /language-(\w+)/.exec(className || '')
        return !inline && match ? (
          
        <div>
            <SyntaxHighlighter> 
              {String(children).replace(/\n$/, '')}
            </SyntaxHighlighter>
             
          </div>
        ) : (
          <code {...props} className={className}>
            {children}
          </code>
        )
      }
    }}
  />
    </div>
  )
}
```

### Expected behavior

I can able to saw the code of children string in the `console` but When i add SyntaxHighlighter It shows me the error. 

### Actual behavior

I tried a lot of ways but it's not working. But a few day's ago the same code was working in my other project, but still not working can you fix it, please?

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm 8

### OS

Linux

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment] 2023-07-26 15:29
Welcome @codergalib2005! 👋 
Sorry you ran into a spot of trouble.
I'm not able to replicate the issue with the code example you provided.
Sandbox of with the code working as expected https://codesandbox.io/s/syntax-highlight-example-x8qt2f

I don't think this is an error in `react-markdown`.
Based off you comment:

> When i add SyntaxHighlighter It shows me the error.

It sounds like it may be an issue coming from `react-syntax-highlighter`.
Some ideas on how to resolve:

1. check to make sure your `next`, `react-markdown`, and `react-syntax-highlighter` are up-to-date with the current latest version.
2. check to ensure you've passed all required options to `react-syntax-highligher`, the example from the README file recommends several additional options https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight
3. Compare the project you have working with the one that is not, see what the differences in build tools, configuration, and structure are.

I'm closing this, are there is nothing for `react-markdown` to fix, the issue is external, most likely in your configuration.
If you have follow up questions about `react-markdown`, feel free to reach out in the discussion forum https://github.com/orgs/remarkjs/discussions.
If you have questions on `react-syntax-highlighter`, feel free to reach out in their discussion forum https://github.com/react-syntax-highlighter/react-syntax-highlighter/discussions

If you believe there is still an issue in `react-markdown` follow the recommendations in https://github.com/remarkjs/.github/blob/main/support.md
In particular focus on:
1. replicating the issue in a way others can also see it (ideally in a sandbox)
2. making that example a minimal reproducible example that shows the issue is in `react-markdown` and not another unrelated package

**Closed as not planned by ChristianMurphy** 2023-07-26 15:29 UTC
Labels: 👀 no/external, 👎 phase/no
