### ISSUE TITLE
htmlParser not working

### ISSUE THREAD

**Issue by fes300** [remarkjs/react-markdown#430] opened 2020-05-20 08:53 UTC
I tried to use a custom `htmlParser` to disallow preprocess HTML but it looks like it is being ignored by `ReactMarkdown`.

here is a snippet reproducing the issue:

```js
const parseHtml = htmlParser({
  isValidNode: () => false,
});

const content = `
This is some paragraph text. 
  - This is a bullet point 
 - This is another one 
 - And a third 

<a href="javascript:alert('hi')">hi</a>

<script>
alert('script')
</script>
`

<ReactMarkdown
  source={content}
  escapeHtml={false}
  linkTarget="_blank"
  astPlugins={[parseHtml]}
/>
```

when I run the above code everything is rendered as usual and `isValidNode` is never called.
Did anyone manage to do this successfully?

**Comment by lukas1994** [comment] 2020-05-25 12:43
Having the same issue. @rexxars any ideas why this is happening?

**Comment by rjernigan** [comment] 2020-05-30 02:12
+1

**Comment by lukas1994** [comment] 2020-06-07 00:27
Any updates? Is this library actively maintained @rexxars ?

**Comment by rexxars** [comment] 2020-06-07 02:02
I'm not able to reproduce. See [this codesandbox](https://codesandbox.io/s/eloquent-moon-1vhkw?file=/src/App.js). As you see in the console, `isValidNode` is called, the script is not included, and the link link is unwrapped. Maybe you were expecting "hi" not to be in the output?

**Comment by fes300** [comment] 2020-06-07 15:17
hi @rexxars, thanks for the answer!
I copy/pasted your exact snippet in my code and:
- `isValidNode` is never called
-`hi` is an anchor with js alert on click. I'll try to reproduce in a sandbox and get back to you   

I'll try to reproduce the bug in a sandbox

**Comment by rjernigan** [comment] 2020-06-07 15:41
The code snippet you posted works for me @rexxars , thanks for following up.  `isValidNode` doesn't fire when I use `useState` however:

```javascript
const parseHtml = htmlParser({
  isValidNode: (node) => {
    console.log("isValidNode called!", node);
    return false;
  },
});

export default () => {
  const [note, setNote] = useState("");

  return (
    <div >
        <textarea
          onChange={(e) => setNote(e.target.value)}
        />
        <ReactMarkdown
          source={note}
          escapeHtml={false}
          astPlugins={[parseHtml]}
        />
    </div>
  );
};
```

Any ideas?

**Comment by ChristianMurphy** [comment] 2020-10-08 21:08
@fes300 I'm not able to reproduce this either.
I'm closing this out for now, if you can reproduce this in a codesandbox we can reopen this and take a look

**Closed by ChristianMurphy** 2020-10-08 21:08 UTC
