### ISSUE TITLE
Typescript compatibility with rehype-raw v7

### ISSUE THREAD

**Issue by Slessi** [remarkjs/react-markdown#763] opened 2023-08-26 19:07 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown 8.0.7 + rehype-raw 7.0.0

### Link to runnable example

https://codesandbox.io/s/beautiful-sound-vthj8w?file=/src/App.tsx

### Steps to reproduce

Just try to use `rehype-raw` v7 with `react-markdown` v8.0.7. I don't know why but the codesandbox version does not reproduce the issue 🙄 but with the same environment locally as in the sandbox, I get it.

Issue seems to be (as far as I can tell) because `rehype-raw` v7 uses `vfile` v6 and/or `unified` v11.

![image](https://github.com/remarkjs/react-markdown/assets/3223500/e084e017-9acb-42d4-9e30-99b090c5eb13)

```
Type '(options?: Options | null | undefined) => (tree: Root, file: VFile) => Root' is not assignable to type 'Pluggable<any[]>'.
  Type '(options?: Options | null | undefined) => (tree: Root, file: VFile) => Root' is not assignable to type 'Plugin<any[], any, any>'.
    Type '(tree: Root, file: VFile) => Root' is not assignable to type 'void | Transformer<any, any>'.
      Type '(tree: Root, file: VFile) => Root' is not assignable to type 'Transformer<any, any>'.
        Types of parameters 'file' and 'file' are incompatible.
          Type 'import("/Users/edward/Projects/tmp/node_modules/vfile/lib/index").VFile' is not assignable to type 'import("/Users/edward/Projects/tmp/node_modules/hast-util-raw/node_modules/vfile/lib/index").VFile'.
            Types of property 'messages' are incompatible.
              Type 'import("/Users/edward/Projects/tmp/node_modules/vfile-message/lib/index").VFileMessage[]' is not assignable to type 'import("/Users/edward/Projects/tmp/node_modules/hast-util-raw/node_modules/vfile-message/lib/index").VFileMessage[]'.
                Type 'VFileMessage' is missing the following properties from type 'VFileMessage': ancestors, placets(2322)
```

### Expected behavior

TS compiles

### Actual behavior

TS errors

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment] 2023-08-26 20:23
Duplicate of https://github.com/unifiedjs/unified/issues/228

**Comment by ChristianMurphy** [comment] 2023-08-26 20:24
The updates are making their way through several hundred packages, for now pin the previous major until the new `react-markdown` major is released

**Closed by ChristianMurphy** 2023-08-26 20:23 UTC
Labels: 🤞 phase/open
