### ISSUE TITLE
editor is crashed when there are nested tags

### ISSUE THREAD

**Issue by annashipilo** [remarkjs/react-markdown#423] opened 2020-05-07 13:46 UTC
Hello! We are using your editor. And we faced such an issue.
If markdown contains something like this `<span><span> ffff </span></span>`
the editor is crashed with such an error in the console

![image](https://user-images.githubusercontent.com/36773373/81301378-a6b0b180-9081-11ea-988e-883d64faee0a.png)

it's also reproduced on the demo here: https://rexxars.github.io/react-markdown/

**Comment by ChristianMurphy** [comment] 2020-05-21 16:29
https://github.com/rexxars/react-markdown/pull/428 resolves this

**Comment by wooorm** [comment] 2020-10-19 10:50
This is also a duplicate of https://github.com/remarkjs/react-markdown/issues/385, so I’ll close this, and we can continue discussing over there

**Closed by wooorm** 2020-10-19 10:50 UTC
Labels: 🐛 type/bug
