### ISSUE TITLE
Issue with rehype-raw v7.0.0

### ISSUE THREAD

**Issue by lewiswolf** [remarkjs/react-markdown#765] opened 2023-08-31 17:53 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.7

### Steps to reproduce

Update to rehype-raw v7.0.0

### Expected behavior

Previous versions did not have this type error.

### Actual behavior

```
error TS2322: Type '(options?: Options | null | undefined) => (tree: Root, file: VFile) => Root' is not assignable to type 'Pluggable<any[]>'.
  Type '(options?: Options | null | undefined) => (tree: Root, file: VFile) => Root' is not assignable to type 'Plugin<any[], any, any>'.
    Type '(tree: Root, file: VFile) => Root' is not assignable to type 'void | Transformer<any, any>'.
      Type '(tree: Root, file: VFile) => Root' is not assignable to type 'Transformer<any, any>'.
        Types of parameters 'file' and 'file' are incompatible.
          Type 'import("/Users/lewiswolstanholme/Desktop/lewiswolstanholme/node_modules/vfile/lib/index").VFile' is not assignable to type 'import("/Users/lewiswolstanholme/Desktop/lewiswolstanholme/node_modules/hast-util-raw/node_modules/vfile/lib/index").VFile'.
            Types of property 'messages' are incompatible.
              Type 'import("/Users/lewiswolstanholme/Desktop/lewiswolstanholme/node_modules/vfile-message/lib/index").VFileMessage[]' is not assignable to type 'import("/Users/lewiswolstanholme/Desktop/lewiswolstanholme/node_modules/hast-util-raw/node_modules/vfile-message/lib/index").VFileMessage[]'.
                Type 'VFileMessage' is missing the following properties from type 'VFileMessage': ancestors, place

rehypePlugins={[rehypeRaw]}
```

**Comment by ChristianMurphy** [comment] 2023-08-31 17:54
Duplicate of https://github.com/remarkjs/react-markdown/issues/763 and https://github.com/unifiedjs/unified/issues/228

**Comment by ChristianMurphy** [comment] 2023-08-31 17:55
The type updates are making their way through several hundred packages, for now pin the previous major until the new `react-markdown` major is released.

**Closed by ChristianMurphy** 2023-08-31 17:54 UTC
Labels: 🤞 phase/open

**Comment by lewiswolf** [comment] 2023-08-31 17:56
sorry for the duplicate! I checked rehype but thought I checked both
