### ISSUE TITLE
TypeScript and Components

### ISSUE THREAD

**Issue by AlbinoGeek** [remarkjs/react-markdown#685] opened 2022-04-19 10:07 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

    "react-markdown": "^8.0.2",
    "remark-directive": "^2.0.1",
    "remark-directive-rehype": "^0.4.0",

### Link to runnable example

https://codesandbox.io/s/dark-water-0vnu6n?file=/src/app.tsx

### Steps to reproduce

See the CodeSandbox. It works, but TypeScript / ESLint prevent builds when using components.

### Expected behavior

Components should be typed to allow extending them beyond known HTML tags.

### Actual behavior

Only known HTML tags can be specified if you want ESLint to let you build.

### Runtime

Node v16

### Package manager

yarn 2

### OS

Linux

### Build and bundle tools

Webpack, Next.js

**Comment by ChristianMurphy** [comment] 2022-04-20 13:20
Thanks, this is a duplicate of https://github.com/remarkjs/react-markdown/issues/622, and in particular see https://github.com/remarkjs/react-markdown/issues/622#issuecomment-888490496
Which in your example would look something like: https://codesandbox.io/s/wizardly-waterfall-8qzygf?file=/src/app.tsx

**Closed** 2022-04-20 13:21 UTC
Labels: 👯 no/duplicate, 👎 phase/no
