### ISSUE TITLE
Input field losing focus `onChange` w/ custom renderer

### ISSUE THREAD

**Issue by PastuDan** [remarkjs/react-markdown#274] opened 2019-02-16 00:21 UTC
I have a custom renderer that generates an input field (below). When the value of the input is changed, it loses focus because the markdown parser seemingly generates new nodes for the input, as well as the parent. What's weird is that React removes and replaces the nodes despite them being exactly the same except for the input's value.

```js
<ReactMarkdown
  source={this.state.content}
  renderers={{
    inlineCode: code => (
      <input
        type="text"
        value={this.state.myInput || code.value}
        onChange={e => {
          this.setState({ myInput: e.target.value })
        }}
      />
    )
  }}
/>
```

I am sure there's a way to resolve this by adding a key in the correct place, but I was hoping someone might have an idea of where to start looking? Similar issue in https://github.com/rexxars/react-markdown/issues/120 but obviously I can't just disable the inputs here.

**Comment by angrybacon** [comment] 2020-03-28 20:06
Having the same issue with `paragraph` where HTML within Markdown will be treated as a paragraph too since blank lines above and below. Said HTML in some case is a tweet embed component where a placeholder has a fixed height (for when the theme changes and it waits for a light/dark themed embed. The height is reset to 0 (initial value for my component) every time the renderer below is utilized.

```jsx
const renderers = {
  /* eslint-disable react/display-name, react/prop-types */
  paragraph: ({ children }) => {
    const component = children[0].type.displayName === 'ParsedHtml' ? 'div' : 'p';
    return <Typography children={children} component={component} gutterBottom />;
  },
  /* eslint-enable react/display-name, react/prop-types */
};
```

If I test with a constructor alone like this:

```jsx
const renderers = {
  paragraph: 'div',
};
```
Or like this:
```jsx
const renderers = {
  paragraph: Typography,
};
```

The same node is *recycled* and my height is left untouched.

Browsing the code, the only difference I can notice has to be in `React.createElement` itself who must behave differently whether you pass it a proper component versus the function I use in my first code block.

**Comment by angrybacon** [comment] 2020-03-28 20:25
Ah! Found it while posting the above.

```jsx
/* eslint-disable react/prop-types */
const Paragraph = ({ children }) => {
  const component = children[0].type.displayName === 'ParsedHtml' ? 'div' : 'p';
  return <Typography children={children} component={component} gutterBottom />;
},
/* eslint-enable react/prop-types */

const renderers = {
  paragraph: Paragraph,
};
```

The renderer simply had to be named. For some reason it doesn't work with shorthand method definitions however.

If someone has

1. the specifics for how are the renderer *cached* I'm interested
1. another way that doesn't involve declaring the renderer (verbose)...

**Comment by ChristianMurphy** [comment] 2020-10-08 21:57
---

@PastuDan does @angrybacon's suggestion work for you?

---

> the specifics for how are the renderer cached I'm interested

I'm not sure what you mean here.
It grabs the renderer and runs it:
https://github.com/remarkjs/react-markdown/blob/c2809c17e9d004abe3fcc3157f6face756323af1/src/ast-to-react.js#L13-L35

caching would be based off the `key`.
this is potentially related to #466 
this behavior would also be changed by #428 

> another way that doesn't involve declaring the renderer

I'm not sure I follow, you want to do custom rendering, without defining a custom renderer?
How would that work?

**Comment by ChristianMurphy** [comment] 2020-10-19 20:30
@PastuDan friendly reminder that this is still waiting for additional information

**Comment by PastuDan** [comment] 2020-10-20 01:49
Unfortunately we removed the code where this was occurring so I can’t test easily. If we do add it back ill give that recommendation a try. Thanks!

**Comment by wooorm** [comment] 2020-10-20 07:53
I am going to close this as it’s not actionable for us. If someone runs into this again, please open a new issue with e.g., a codesandbox so we can reproduce it!

**Closed by wooorm** 2020-10-20 07:53 UTC
Labels: 🧘 status/waiting
