### ISSUE TITLE
How to enable remark-slug plugin?

### ISSUE THREAD

**Issue by sunknudsen** [remarkjs/react-markdown#397] opened 2020-03-06 15:05 UTC
The following code doesn’t throw an error but id’s are not added to headings.

Also tried `plugins={[[require("remark-slug")]]}`.

```typescript
<ReactMarkdown
  source={source}
  plugins={[require("remark-slug")]}
/>
```

**Comment by shyaniv7** [comment] 2020-03-25 18:48
I think it would be

```
import slug from 'remark-slug';

<ReactMarkdown
  source={source}
  plugins={[slug]}
/>
```

which is essentially the same as your example. I have the same working using the remark-toc plugin

**Comment by sunknudsen** [comment] 2020-03-26 11:27
Hey @shyaniv7, thanks for helping out. Unfortunately, I believe what you are suggesting is identical to using `plugins={[require("remark-slug")]}` and it doesn’t work. No errors are thrown, but ids are not added to the heading tags.

**Comment by shyaniv7** [comment] 2020-03-26 14:35
> Hey @shyaniv7, thanks for helping out. Unfortunately, I believe what you are suggesting is identical to using `plugins={[require("remark-slug")]}` and it doesn’t work. No errors are thrown, but ids are not added to the heading tags.

Hey @sunknudsen, if what youre trying to do is add id="<slug>" to your <h > tags check out my answer here https://github.com/rexxars/react-markdown/issues/404 you can override the heading node renderer

**Comment by sunknudsen** [comment] 2020-03-27 13:15
Thanks for sharing @shyaniv7.

I ended up overriding the heading as you suggested but using [github-slugger](https://www.npmjs.com/package/github-slugger).

```typescript
interface HeadingProps {
  level: number
  children: JSX.Element[]
}

const Heading: FunctionComponent<HeadingProps> = function(props) {
  return React.createElement(
    `h${props.level}`,
    {
      id: slug(props.children[0].props.children),
    },
    props.children
  )
}
```

**Comment by Madsim** [comment] 2020-05-07 10:42
I have the same problem. Tracked it down to the renderers as well. It seems the data field on nodes is just ignored and not added to the prop set. Is there a specific reason for that @rexxars? I could provide a feature to allow, at least a few importand and react safe attributes from node.data.

**Comment by ChristianMurphy** [comment] 2020-10-08 20:46
This appears to be a duplicate of #384, since remark-slug uses hProperties to set the id.
The resolution will be #428, closing this in favor of #384 since it is more specific.

**Closed by ChristianMurphy** 2020-10-08 20:46 UTC
