### ISSUE TITLE
When using two **enclosed bold texts containing colons, react-markdown fails to correctly parse the bold syntax.

### ISSUE THREAD

**Issue by luichooy** [remarkjs/react-markdown#824] opened 2024-04-01 15:49 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@9.0.0

### Steps to reproduce

1. open the [react-markdown example url](https://codesandbox.io/p/devbox/adoring-hoover-gnc9vj?file=%2Fpackage.json%3A10%2C25-10%2C30) or [micromark example url](https://stackblitz.com/edit/stackblitz-starters-am2dx6?file=index.js) to observe the output

### Expected behavior

```html
<p><strong>人工智能的潜在好处</strong></p>
<ul>
<li><strong>提高生产力：</strong>人工智能可以自动化任务，解放人类劳动力专注于更有创造性和战略性的工作。</li>
<li><strong>hello：</strong>人工智能可以分析大量数据，识别模式并提供基于数据的见解，从而帮助人们做出更好的决策。</li>
<li><strong>hello:</strong>人工智能可以定制产品和服务，以满足个人的需求和偏好。</li>
<li><strong>world</strong>人工智能可以帮助诊断疾病，开发新疗法，并改善患者护理。</li>
<li><strong>hello world</strong>人工智能可以处理大量数据，发现人类可能无法自行发现的模式和见解。</li>
</ul>
```

### Actual behavior

```html
<p><strong>人工智能的潜在好处</strong></p>
<ul>
<li>**提高生产力：**人工智能可以自动化任务，解放人类劳动力专注于更有创造性和战略性的工作。</li>
<li>**hello：**人工智能可以分析大量数据，识别模式并提供基于数据的见解，从而帮助人们做出更好的决策。</li>
<li>**hello:**人工智能可以定制产品和服务，以满足个人的需求和偏好。</li>
<li><strong>world</strong>人工智能可以帮助诊断疾病，开发新疗法，并改善患者护理。</li>
<li><strong>hello world</strong>人工智能可以处理大量数据，发现人类可能无法自行发现的模式和见解。</li>
</ul>
```

### Runtime

Node v17

### Package manager

pnpm

### OS

Windows, macOS

### Build and bundle tools

Webpack, Create React App

**Comment by ChristianMurphy** [comment] 2024-04-01 16:41
Duplicate of https://github.com/micromark/micromark/issues/41

**Closed as not planned by ChristianMurphy** 2024-04-01 16:41 UTC
Labels: 🤞 phase/open

**Comment by ChristianMurphy** [comment] 2024-04-01 16:42
To copy over the response there for clarity here:

> your "incorrect" example is what CommonMark does too. We follow CM, so this is not an issue in micromark but one in CM.
>
> https://github.com/commonmark/commonmark-spec/issues/650 seems to be the issue, and also https://github.com/commonmark/commonmark-spec/issues/488 might be related.
