### ISSUE TITLE
process.cwd is not a function

### ISSUE THREAD

**Issue by MichaelKheel** [remarkjs/react-markdown#492] opened 2020-10-20 19:27 UTC
Hello, after switching to **webpack 5**, I just can't get this module to work, I tried everything possible, added polyfills to the webpack settings, added the module require('process') to the /core.js . Tell me how you can get it to work at least temporarily?

```
Uncaught TypeError: process.cwd is not a function
    at new VFile (vendors-node_modules_material-ui_icons_esm_EventAvailable_js-node_modules_material-ui_icons_e-69977d.bundle.3539fc11cce8d41811bd.js:10184)
    at VFile (vendors-node_modules_material-ui_icons_esm_EventAvailable_js-node_modules_material-ui_icons_e-69977d.bundle.3539fc11cce8d41811bd.js:10178)
    at Function.parse (vendors-node_modules_material-ui_icons_esm_EventAvailable_js-node_modules_material-ui_icons_e-69977d.bundle.3539fc11cce8d41811bd.js:9384)
    at ReactMarkdown (vendors-node_modules_material-ui_icons_esm_EventAvailable_js-node_modules_material-ui_icons_e-69977d.bundle.3539fc11cce8d41811bd.js:8500)
    at renderWithHooks (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:79814)
    at mountIndeterminateComponent (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:82493)
    at beginWork (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:83607)
    at HTMLUnknownElement.callCallback (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:65199)
    at Object.invokeGuardedCallbackDev (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:65248)
    at invokeGuardedCallback (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:65303)
    at beginWork$1 (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:88214)
    at performUnitOfWork (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:87165)
    at workLoopSync (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:87141)
    at performSyncWorkOnRoot (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:86767)
    at vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:76100
    at unstable_runWithPriority (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:104976)
    at runWithPriority$1 (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:76050)
    at flushSyncCallbackQueueImpl (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:76095)
    at flushSyncCallbackQueue (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:76083)
    at scheduleUpdateOnFiber (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:86210)
    at dispatchAction (vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-c70d23.bundle.15c7cbcdd7af9de1ef55.js:80671)
    at src_pages_releases_jsx.bundle.5da1a3c4fe86fc0c934a.js:102
```

![image](https://user-images.githubusercontent.com/26508094/96633780-cbed5f80-1343-11eb-9dc6-1b6bd7dc7ed8.png)

**Comment by ChristianMurphy** [comment] 2020-10-20 19:33
This is a duplicate of https://github.com/remarkjs/react-markdown/issues/339
see https://github.com/remarkjs/react-markdown/issues/339#issuecomment-683199835 for the solution

**Closed by ChristianMurphy** 2020-10-20 19:33 UTC
Labels: 🐛 type/bug, 🔍 status/open
