### ISSUE TITLE
toolbar

### ISSUE THREAD

**Issue by sm-hejazi** [remarkjs/react-markdown#735] opened 2023-04-05 12:29 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

How to add toolbar
like this image:

![example](https://user-images.githubusercontent.com/1094760/33604369-0e5b5c50-d9f9-11e7-9608-43390260bf3e.png)

### Solution

add toolbar 

### Alternatives

add plugin

**Comment by wooorm** [comment] 2023-04-05 12:37
Duplicate of remarkjs/remark#1144

**Closed by wooorm** 2023-04-05 12:37 UTC
Labels: 🤞 phase/open
