### ISSUE TITLE
feature-request: Support passing hProperties to renderers

### ISSUE THREAD

**Issue by bj00rn** [remarkjs/react-markdown#384] opened 2020-01-23 14:55 UTC
I was hoping to be able to use the [remark-attr](https://github.com/arobase-che/remark-attr) plugin in order to pass attributes from markdown.

`remark-attr` plugin supports declaring attributes on elements like so:
```
### This is a title
{id="maintitle" style="color:red;"}
```

These properties are parsed correctly by the plugin into `node.data.hProperties` However, properties are not passed on by `react-markdown` to the renderers.

## ast-to-react.js

![image](https://user-images.githubusercontent.com/10961167/72994663-cfc17500-3df7-11ea-9161-08b668bf2c8f.png)

Passing on hProperties would be nice, but maybe it has some security implications.

**Comment by arobase-che** [comment] 2020-01-23 17:59
About the security aspect. remark-attr handle a lot of that part. It uses a whitelist approach.

By default, only standard attributes not even based are allowed.

**Comment by mrm007** [comment] 2020-01-23 22:59
In the meantime, if you like hacks (and who doesn't?) I have this workaround in my project:

- pass `rawSourcePos={true}` to `ReactMarkdown`
- create a map `imageNodes` to store references to your `image` nodes (see code below)
- pass a function to `allowNodes` that saves references to `image` nodes
- have a custom `image` renderer which looks up the corresponding node in `imageNodes` (the node contains `data.hProperties`)

```js
function MyMarkdown(props) {
  const imageNodes = new Map();
  const nodeKey = position => JSON.stringify(position.start); // or use a custom hash function

  function allowNodes(node) {
    if (node.type === "image") imageNodes.set(nodeKey(node.position), node);
    return true;
  }

  const renderers = {
    image({ sourcePosition, alt, src, title }) {
      const node = imageNodes.get(nodeKey(sourcePosition));
      return (
        <img alt={alt} src={src} title={title} {...node.data.hProperties} />
      );
    }
  };

  return (
    <ReactMarkdown
      {...props}
      allowNodes={allowNodes}
      renderers={renderers}
      rawSourcePos
    />
  );
}
```

You don't need to clean up `imageNodes` because it will be recreated and disposed on every render.

**Comment by bostrom** [comment] 2020-05-19 13:24
Yes, `remark-attr` support would be great!

**Comment by jacobwicks** [comment] 2020-06-19 21:40
> In the meantime, if you like hacks (and who _doesn't_?) I have this workaround in my project:
> ...

I used this code to resize images in a project I'm making. I did a short writeup of it on my blog here: 

https://jacobwicks.github.io/2020/06/19/rendering-markdown-and-resizing-images-with-react-markdown.html

Thanks for the example!

**Comment by ChristianMurphy** [comment] 2020-10-08 15:49
this will be resolved by #428 which leverages remark-rehype which handles hProperties

**Closed** 2021-04-12 06:31 UTC
Labels: 🦋 type/enhancement

**Comment by wooorm** [comment] 2021-04-12 18:13
This should be solved by landing GH-563 today, which will soon be released in v6.0.0!

**Comment by colophonemes** [comment] 2021-04-19 17:26
Is there a trick to using this (other than passing `remark-attr` to the `remarkPlugins` array? The following isn't working for me:

```ts
import React from 'react'
import ReactMarkdown from 'react-markdown'
import attributes from 'remark-attr'
import behead from 'remark-behead'
import slug from 'remark-slug'

const REMARK_PLUGINS = [
  [behead, { depth: 1 }],
  [slug],
  [attributes],
]

const Markdown = ({ children }) => {
	<ReactMarkdown
      remarkPlugins={REMARK_PLUGINS}
    >
        {children}
      </ReactMarkdown>
}
```

But this results in the following error:

```
Error: Missing parser to attach `remark-attr` [link] (to)
```

This looks like it's caused by [this check](https://github.com/arobase-che/remark-attr/blob/master/src/index.js#L315) in `remark-attr`, which calls the following function:

```js
function isRemarkParser(parser) {
  return Boolean(
    parser &&
    parser.prototype &&
    parser.prototype.inlineTokenizers &&
    parser.prototype.inlineTokenizers.link &&
    parser.prototype.inlineTokenizers.link.locator,
  );
}
```


(This might be an issue with the `remark-attr` implementation, so let me know if this is the case and I'll open an issue there)

**Comment by wooorm** [comment] 2021-04-19 17:30
`remark-attr` has not updated to the latest parser. See status indications for plugins in the [list of plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins). And the issue tracker on that project.

**Comment by colophonemes** [comment] 2021-04-19 17:34
@wooorm thanks so much for the quick response, will keep an eye on that page!

**Comment by arobase-che** [comment] 2021-04-19 18:36
I plan to update `remark-attr` before September. No guarantee.
As it's need for my use case.

If someone wants deadline or support. We may find a monetary arrangement. Otherwise,I think @wooorm has pretty good alternatives. :)
