### ISSUE TITLE
rehype-raw 7.0.0 seems not supported

### ISSUE THREAD

**Issue by erwan-joly** [remarkjs/react-markdown#769] opened 2023-09-11 00:40 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.7

### Steps to reproduce
```

With 7.0.0 the readme does not work anymore

import React from 'react'
import ReactDom from 'react-dom'
import ReactMarkdown from 'react-markdown'
import rehypeRaw from 'rehype-raw'

const input = `<div class="note">

Some *emphasis* and <strong>strong</strong>!

</div>`

ReactDom.render(
  <ReactMarkdown rehypePlugins={[rehypeRaw]} children={input} />,
  document.body
)

```
### Expected behavior

no error 

### Actual behavior

we get this error TS2322	(TS) Type '(options?: Options) => (tree: Root, file: VFile) => Root' is not assignable to type 'Pluggable<any[]>'

**Comment by ChristianMurphy** [comment] 2023-09-11 00:46
Duplicate of https://github.com/remarkjs/react-markdown/issues/763

**Comment by ChristianMurphy** [comment] 2023-09-11 00:46
The updates are making their way through several hundred packages, for now pin the previous major until the new `react-markdown` major is released

**Closed by ChristianMurphy** 2023-09-11 00:46 UTC
Labels: 👯 no/duplicate, 🤞 phase/open
