### ISSUE TITLE
Tables are not rendered correctly for readme

### ISSUE THREAD

**Issue by PuneetPunamiya** [remarkjs/react-markdown#532] opened 2021-01-15 07:34 UTC
### Subject of the issue

Tables are not rendered correctly for readme

I have created an example [here](https://github.com/PuneetPunamiya/markdown)

The basic gist of the issue is:

We are fetching the raw readme and the need is to render the readme in proper format on UI

The table in the readme appears to be 

![image](https://user-images.githubusercontent.com/32545638/104694549-5e2db580-5731-11eb-911d-1f5ea7d71b9b.png)

But using `react-markdown` and `syntax-highlighter` it renders on UI as follows 

![image](https://user-images.githubusercontent.com/32545638/104694642-80273800-5731-11eb-8374-32c7348520a8.png)

This is *not* a place to ask questions.  For that, go to [discussions](https://github.com/remarkjs/remark/discussions)

### Your environment

*   **OS**:   Linux
*   **Packages**: 

```
{
  "name": "markdown",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.53",
    "@types/react-dom": "^16.9.8",
    "@types/react-syntax-highlighter": "^13.5.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-markdown": "^5.0.2",
    "react-scripts": "4.0.0",
    "react-syntax-highlighter": "^15.3.0",
    "typescript": "^4.0.3",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

### Steps to reproduce

1. Fork/Clone the project [here](https://github.com/PuneetPunamiya/markdown)
2. Run the command  `npm install`
3. Readme should render on ui as it is [here](https://github.com/tektoncd/catalog/blob/master/task/tkn/0.2/README.md)

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

What should happen?

### Actual behavior

What happens instead?

**Comment by chipcop106** [comment] 2021-01-15 09:47
I have the same issues, how to fix them?

**Comment by wooorm** [comment] 2021-01-15 11:22
duplicate of #529, #526, #525, #524, #516, and #493

how to use tables (and the rest of GitHub Flavored Markdown) is documented in the readme https://github.com/remarkjs/react-markdown#use
As for the demo site, it does not include remark-gfm and therefore doesn't render tables.

**Closed by wooorm** 2021-01-15 11:22 UTC
Labels: 🐛 type/bug, 🔍 status/open

**Comment by PuneetPunamiya** [comment] 2021-01-15 11:58
@wooorm  Thanks a lot for this, was really helpful. Just one question, using the remark-gfm renders tables, but is there a way or options where border for the tables also renders

**Comment by wooorm** [comment] 2021-01-15 12:41
This project does not concern itself with styling. You can use things like CSS to style the results!

**Comment by PuneetPunamiya** [comment] 2021-01-18 04:18
> This project does not concern itself with styling. You can use things like CSS to style the results!

Thanks @wooorm  for your help :hugs:
