### ISSUE TITLE
Using react-markdown with Next.js 15 app dir results in error

### ISSUE THREAD

**Issue by steebchen** [remarkjs/react-markdown#869] opened 2024-10-26 17:28 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.1

### Steps to reproduce

Use Next.js >=15.0.0 and render `<Markdown>...</Markdown>` in a server component.

NOTE: adding `use client` in the component which renders Markdown fixes the build, however any route will always return 500 even though it still renders fine.

### Expected behavior

No error. It works fine in Next 14.

### Actual behavior

```
Error: Failed to collect configuration for /product/[id]/[slug]
    at /Users/a/b/c/node_modules/.pnpm/next@15.0.1_@babel+core@7.25.8_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/utils.js:1130:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Users/a/b/c/node_modules/.pnpm/next@15.0.1_@babel+core@7.25.8_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:157:20) {
  [cause]: ReferenceError: document is not defined
      at 29265 (/Users/a/b/c/.next/server/edge-chunks/829.js:1:52366)
      at t (/Users/a/b/c/.next/server/edge-runtime-webpack.js:1:485)
      at 78130 (/Users/a/b/c/.next/server/app/product/[id]/[slug]/page.js:1:28452)
      at t (/Users/a/b/c/.next/server/edge-runtime-webpack.js:1:485)
      at 27165 (/Users/a/b/c/.next/server/app/product/[id]/[slug]/page.js:1:3661)
      at Function.t (/Users/a/b/c/.next/server/edge-runtime-webpack.js:1:485)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}

> Build error occurred
Error: Failed to collect page data for /product/[id]/[slug]
    at /Users/a/b/c/node_modules/.pnpm/next@15.0.1_@babel+core@7.25.8_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/utils.js:1233:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.
````

### Affected runtime and version

node v20

### Affected package manager and version

pnpm v9.12.0

### Affected OS and version

macos

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment] 2024-10-26 19:49
Welcome @steebchen! 👋 
Sorry you ran into a spot of trouble.

This project doesn't use `document` https://github.com/search?q=repo%3Aremarkjs%2Freact-markdown+document&type=code

The error is coming from somewhere else.
My guess is that next.js isn't correctly resolving exports for a dependency somewhere and chose the browser version instead of the server version.

**Comment by steebchen** [comment] 2024-10-26 21:55
Hmm it's super weird. I can basically comment this out and it works fine:

<img width="715" alt="IntelliJ IDEA 2024-10-26 22 53 11" src="https://github.com/user-attachments/assets/d2acd9f3-8f4e-447a-9b1e-ebc0a37051b1">

<img width="716" alt="IntelliJ IDEA 2024-10-26 22 53 26" src="https://github.com/user-attachments/assets/0c764d48-997f-4538-b5be-84831c6e64ff">

It is the same when my markdown content is just `foo` or something.

Any idea how I could figure out how an other dependency might be related?

**Comment by wooorm** [comment] 2024-10-28 10:18
Closing as you indicate this is related to a very new Next 15; not Next 14; I haven’t seen this outside of Next. The problem and the fix are probably in Next 15. Not here.

Issues are for issues. General debugging help can go in other places.

I would recommend asking the multi-million dollar company for help with their new tools that do complex resolving things, which sounds like where the bug is.

**Closed by wooorm** 2024-10-28 10:18 UTC
Labels: 🤞 phase/open

**Comment by ChristianMurphy** [comment] 2025-03-24 17:55
@marhaupe I'd recommend opening up a Q&A discussion https://github.com/orgs/remarkjs/discussions/new?category=q-a
Same as noted above, `document` does not appear in this project, this is not a bug of this project.
It is of the resolution rules you are using in your build tool.

I suspect the key in this is:
> cloudflare project

You may be doing some server side rendering, but are selecting the client side version of the dependencies of the project. That is a vite configuration issue, not a `react-markdown` issue.

**Comment by marhaupe** [comment] 2025-03-25 09:59
You're right. It boils down to the wrong version of https://github.com/wooorm/decode-named-character-reference being used during SSR. If I figure out a fix, I'll post an update in case more people are struggling with this. 

Regardless of whether it is a react-markdown issue or not, people will keep showing up here with questions, especially with the push to SSR everything and the fact that client-server boundaries get blurrier and blurrier.

**Comment by remcohaszing** [comment] 2025-03-25 10:08
Coincidentally I integrated `react-markdown` into a Next.js project without any problems last week. It just works. If someone runs into these problems, it's likely due to outdated dependencies.

**Comment by wooorm** [comment] 2025-03-25 10:18
Probably https://github.com/wooorm/decode-named-character-reference/pull/6.

@marhaupe You can probably configure cloudflare, or PR/raise an issue with clouflare, or similarly accommodate cloudflare.

**Comment by marhaupe** [comment] 2025-03-25 18:16
Just leaving it here because I'm surrendering and maybe it'll help the poor soul who happens to struggle with something similar: 

`@cloudflare/vite-plugin` seems to set their `resolve.conditions` to `["workerd", "module", "browser"]`. `decode-named-character-reference` does not export a `workerd` package, so they resolve the `browser` version. Fair enough. Monkey patching the fix in https://github.com/wooorm/decode-named-character-reference/pull/6 is easy enough with `pnpm patch decode-named-character-reference@1.1.0`, and that actually fixed the faulty module resolution, but apparently opened a whole other can of worms that I'm not ready to tackle (yet). God bless all of you who seem to have figured out how to navigate the mess the JS ecosystem is because this is... not fun. 

That being said, I appreciated all of your input on this! I'll consider raising an issue in the appropriate repo, once I'm sure what the actual culprit of all of this is.

**Comment by ChristianMurphy** [comment] 2025-03-25 18:20
This would probably go up to https://github.com/wooorm/decode-named-character-reference
We can add conditions for new environment types, sounds like we now know `workerd` is the one for cloudflare.
For folks on the NextJS side, do some research on which you need, and how it is different from https://github.com/wooorm/decode-named-character-reference/pull/6

**Comment by valeriangalliat** [comment] 2025-03-27 18:23
Also encountered this issue on Next 15 and fixed it with

```
const Markdown = dynamic(() => import("react-markdown"), { ssr: false })
```

**Comment by HananoshikaYomaru** [comment] 2025-06-02 20:22
> Just leaving it here because I'm surrendering and maybe it'll help the poor soul who happens to struggle with something similar:
> 
> `@cloudflare/vite-plugin` seems to set their `resolve.conditions` to `["workerd", "module", "browser"]`. `decode-named-character-reference` does not export a `workerd` package, so they resolve the `browser` version. Fair enough. Monkey patching the fix in [wooorm/decode-named-character-reference#6](https://github.com/wooorm/decode-named-character-reference/pull/6) is easy enough with `pnpm patch decode-named-character-reference@1.1.0`, and that actually fixed the faulty module resolution, but apparently opened a whole other can of worms that I'm not ready to tackle (yet). God bless all of you who seem to have figured out how to navigate the mess the JS ecosystem is because this is... not fun.
> 
> That being said, I appreciated all of your input on this! I'll consider raising an issue in the appropriate repo, once I'm sure what the actual culprit of all of this is.

since you have already identified the issue, I think rather than patching `decode-named-character-reference`, the correct way to handle this is to patch `@cloudflare/vite-plugin`.
