### ISSUE TITLE
Github style table  is not rendered correctly while using remark-gfm

### ISSUE THREAD

**Issue by detectiveHLH** [remarkjs/react-markdown#733] opened 2023-03-17 03:38 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown: "^8.0.5" remark-gfm: "^3.0.1"

### Steps to reproduce

I'm using react-gfm to render Table, I using the same markdown text in [official demo](https://remarkjs.github.io/react-markdown/), but it's not working like it.
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/24632081/225806111-48cd770d-d462-45ed-ad6e-77b7fa2bbaf4.png">
It should be:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/24632081/225806164-133db86c-d450-475b-aac6-3b5d1526f531.png">
My code is like this:
```javascript
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
.....
<ReactMarkdown
  remarkPlugins={[remarkGfm, remarkRehype]}
>
  {mdSourceText}
</ReactMarkdown>
```

### Expected behavior

Tables are rendered in Github style

### Actual behavior

Actual like this:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/24632081/225806561-ebd510ec-324b-4d4e-8bee-3b63905b839f.png">

I also using a sanbox to test it, but I got the same problem:[sanbox link](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-create-react-app?file=/src/app.tsx:599-608)

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment] 2023-03-17 09:23
Use CSS. You don‘t have CSS.

Duplicate of #631

**Closed by wooorm** 2023-03-17 09:23 UTC
Labels: 🤞 phase/open
