### ISSUE TITLE
Compatible with lower version browsers

### ISSUE THREAD

**Issue by 51wangping** [remarkjs/react-markdown#839] opened 2024-07-08 07:48 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.1

### Link to runnable example

demo: https://github.com/51wangping/test-react-markdown

### Steps to reproduce

I will write a dmeo and publish it on github
adress: https://github.com/51wangping/test-react-markdown

### Expected behavior

Can be used in lower version browsers

### Actual behavior

I use react-mardown and it doesn't work in lower version browsers

The browser version I am using:  Chromium 63.0.3239.0

### Runtime

Node v17

### Package manager

yarn 2

### OS

macOS

### Build and bundle tools

Webpack

**Comment by remcohaszing** [comment] 2024-07-08 07:55
Duplicate of #822

**Closed by remcohaszing** 2024-07-08 07:55 UTC
Labels: 🤞 phase/open
