### ISSUE TITLE
Code highliting with react-syntax-highlighter bug

### ISSUE THREAD

**Issue by Toavina23** [remarkjs/react-markdown#807] opened 2024-01-03 08:24 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.1

### Steps to reproduce

I just copy pasted the example from readme for code syntax highlithing to my code

### Expected behavior

should higlight the code correctly

### Actual behavior

![image](https://github.com/remarkjs/react-markdown/assets/71165799/ed48a1eb-317c-4acd-9e74-491422c38f35)
the code blocks are looking like in the image above instead of showing the code

### Package manager

npm 8

### OS

Windows

**Comment by wooorm** [comment] 2024-01-03 09:11
You need to show code. I cant look into your computer…

**Comment by ChristianMurphy** [comment] 2024-01-30 15:01
@Toavina23 friendly ping 🔔 
This still needs a way to reproduce the issue you are seeing.

**Comment by Toavina23** [comment] 2024-02-05 15:52
Hello, 

Sorry for the late reply,
after checking my code, the problem was that I was using two plugins that confilicted and gave this error.

**Comment by ChristianMurphy** [comment] 2024-02-05 16:42
Thanks for following up @Toavina23!
Glad you tracked down the cause.
I'll close this ticket as it seems to be an external issue.

Though it could still be helpful to post which two plugins had a conflict and how you resolved it so future developers can benefit from your findings.

**Closed by ChristianMurphy** 2024-02-05 16:42 UTC
Labels: 🤞 phase/open, 🙊 open/needs-repro
