### ISSUE TITLE
Request: React 18 support for "children" prop

### ISSUE THREAD

**Issue by justindeocampodd** [remarkjs/react-markdown#729] opened 2023-02-27 23:45 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.5

### Steps to reproduce

The occurring error is:
```
<ReactMarkdown>
        {
          somePropHere
        }
</ReactMarkdown>
```

```
No overload matches this call.
  Overload 1 of 2, '(props: ReactMarkdownProps | Readonly<ReactMarkdownProps>): ReactMarkdown', gave the following error.
    Type '{ children: string | null | undefined; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactMarkdown> & Readonly<ReactMarkdownProps>'.
  Overload 2 of 2, '(props: ReactMarkdownProps, context: any): ReactMarkdown', gave the following error.
    Type '{ children: string | null | undefined; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactMarkdown> & Readonly<ReactMarkdownProps>'. ts(2769)
```

This happens when using React-Markdown on any version of React 18.x.

### Expected behavior

Expect the ReactMarkdown component to work on React 18.

### Actual behavior

We get this type error because there is no "children" prop included in the ReactMarkDownProps. We can fix this by editing the ReactMarkdown class in the index.ts file to be:
`class ReactMarkdown extends Component<React.PropsWithChildren<ReactMarkdown.ReactMarkdownProps>, {}> {}`

or to include a children prop in ReactMarkdownProps manually.

### Runtime

Node v14

### OS

macOS

**Comment by ChristianMurphy** [comment] 2023-02-27 23:52
Welcome @justindeocampodd!
This is a duplicate of https://github.com/remarkjs/react-markdown/issues/711, closing in favor of the existing ticket.
PRs resolving the issue are welcome!

**Closed by ChristianMurphy** 2023-02-27 23:52 UTC
Labels: 🤞 phase/open

**Comment by wooorm** [comment] 2023-02-28 08:50
Duplicate of #711
