### ISSUE TITLE
Add possibility to send extra props to custom components

### ISSUE THREAD

**Issue by lucasMarioza** [remarkjs/react-markdown#746] opened 2023-06-14 15:02 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently, you can't send extra data from the parent component to the custom components through props. This force you to define the the custom component inside the parent component, which is an anti-pattern because cause the redefinition of the custom component every re-render, which makes react understand that it is a different component every re-render, causing detachment and as consequence possible performance issues and state loss(if for some reason your custom component has state in it).

Using the [read me example](https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight):
let's say that instead of having the `dark` style, the parent component receive it as prop

```js
function MyMarkdownBlock({highlighterTheme}) {
  return (
    <ReactMarkdown
        children={markdown}
        components={{
          code({node, inline, className, children, ...props}) {
            const match = /language-(\w+)/.exec(className || '')
            return !inline && match ? (
              <SyntaxHighlighter
                {...props}
                children={String(children).replace(/\n$/, '')}
                style={highlighterTheme /* I'm forced to use it directly from the parent component which makes impossible to extract this component definition to outside of the parent */} 
                language={match[1]}
                PreTag="div"
              />
            ) : (
              <code {...props} className={className}>
                {children}
              </code>
            )
          }
        }}
    />
  );
}
```

### Solution

Add a `componentsExtraProps` prop to `ReactMarkdown` that will be passed to the custom components.

in the example mentioned above, it would look like this

```js
function MyCodeComponent({node, inline, className, children, extraProps, ...props}) {
  const match = /language-(\w+)/.exec(className || '')
  const {highlighterTheme} = extraProps /* now it's part of the custom component and I can extract it*/
  return !inline && match ? (
    <SyntaxHighlighter
      {...props}
      children={String(children).replace(/\n$/, '')}
      style={highlighterTheme} 
      language={match[1]}
      PreTag="div"
    />
  ) : (
    <code {...props} className={className}>
      {children}
    </code>
  )
}

function MyMarkdownBlock({highlighterTheme}) {
  return (
    <ReactMarkdown
        children={markdown}
        componentsExtraProps={{highlighterTheme}}
        components={{
          code: MyCodeComponent
        }}
    />
  );
}
```

### Alternatives

The workaround for that is using another way of sharing data, with Contexts for example

it would look like this
```js
const Context = React.createContext();

function MyCodeComponent({node, inline, className, children, extraProps, ...props}) {
  const match = /language-(\w+)/.exec(className || '')
  const {highlighterTheme} = useContext(Context)
  return !inline && match ? (
    <SyntaxHighlighter
      {...props}
      children={String(children).replace(/\n$/, '')}
      style={highlighterTheme} 
      language={match[1]}
      PreTag="div"
    />
  ) : (
    <code {...props} className={className}>
      {children}
    </code>
  )
}

function MyMarkdownBlock({highlighterTheme}) {
  return (
    <Context.Provider value={{highlighterTheme}}>
      <ReactMarkdown
          children={markdown}
          components={{
            code: MyCodeComponent
          }}
      />
   </Context.Provider>
  );
}
```

Although it works, it still make the custom component too coupled to the parent component and makes it hard to share it with some other places.

**Comment by wooorm** [comment] 2023-06-14 15:25
This is how React works. You can memo things.
I believe this is a duplicate of https://github.com/remarkjs/react-markdown/issues/684, which also references https://github.com/rehypejs/rehype-react/issues/38

Duplicate of #684

**Comment by wooorm** [comment] 2023-06-14 15:25
Duplicate of #684

**Closed by wooorm** 2023-06-14 15:25 UTC
Labels: 🤞 phase/open
