### ISSUE TITLE
Can't identify single line and multiline code block differently

### ISSUE THREAD

**Issue by sanjayrajpurohit36** [remarkjs/react-markdown#880] opened 2024-12-22 21:45 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

While using the react-markdown I ran into a probem that what if I want to render two different component for multiline and singleline code block.
Like `code` should be treated differently and 
```javascript 
console.log(10)
``` 
 should render a different component, in that case how I can identify that.
 

### Current solutions

I was not able to find any solution.

### Proposed solutions

There should be some custom name to identify such case like that we have for other html elements.

**Comment by ChristianMurphy** [comment] 2024-12-22 22:41
Duplicate of https://github.com/orgs/remarkjs/discussions/1346

**Comment by ChristianMurphy** [comment] 2024-12-22 22:41
It is possible please see the discussion linked above

**Closed by ChristianMurphy** 2024-12-22 22:41 UTC
Labels: 🤞 phase/open
