### ISSUE TITLE
Misidentify table contents

### ISSUE THREAD

**Issue by 13832198312** [remarkjs/react-markdown#850] opened 2024-08-08 03:21 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"remark-gfm": "^4.0.0", "react-markdown": "^9.0.1",

### Steps to reproduce

The last sentence should not be the table ,but in the table

### Expected behavior

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/45f2c68c-dad2-4b41-ae78-6453e3a33e3b">

The last sentence should not be the table like right

### Actual behavior

<img width="748" alt="image" src="https://github.com/user-attachments/assets/a17c0cfa-cd3e-46ec-b0e0-b315ef721512">
but like this

### Runtime

Node v17

**Comment by ChristianMurphy** [comment] 2024-08-08 04:34
Duplicate of https://github.com/orgs/remarkjs/discussions/1352

**Closed by ChristianMurphy** 2024-08-08 04:34 UTC
Labels: 🤞 phase/open
