### ISSUE TITLE
Mismatch of types for the renderers

### ISSUE THREAD

**Issue by n-lam** [remarkjs/react-markdown#527] opened 2020-12-31 11:17 UTC
### Mismatch of types for the renderers

Describe your issue here.

When using the expected typing for custom renderers, it causes an error in the Typescript compiler

### Your environment

*   **OS**: Linux 20.04.1
*   **Packages**: react-markdown (4.3.1)
*   **Env**: node 14.4.0, yarn 1.22.4

### Expected behavior

When creating custom renderers, the type should be 'Renderers'.

```
const renderers: Renderers = {
  image: ImgRenderer,
};
```

### Actual behavior

When the type Renderers is used, the Typescript compiler says that 'No overload matches this call'.

```
<ReactMarkdown source={text} renderers={renderers} />
```

**Comment by n-lam** [comment] 2020-12-31 11:21
I believe the solution would be to update the ReactMarkdownProps interface.

Old:
```
readonly renderers?: {[nodeType: string]: ReactType}
```

New:
```
readonly renderers?: Renderers
```

**Comment by ChristianMurphy** [comment] 2020-12-31 13:38
duplicate of #327

**Closed by ChristianMurphy** 2020-12-31 13:38 UTC
Labels: 🐛 type/bug, 🔍 status/open
