### ISSUE TITLE
Question: elegantly handling errors

### ISSUE THREAD

**Issue by SircleCquare** [remarkjs/react-markdown#306] opened 2019-05-13 01:56 UTC
### Context: 

We had some bad HTML in one of our documents that looked something like this: 
```
[title](link)</br>
[title](link)</br>
[title](link)
```
Since `</br>` isn't valid, we got an exception: `TypeError: Cannot read property \'props\' of undefined`, and the whole page didn't render 

### Question: 

The exception is our fault, but we'd like to be able to handle the error more elegantly. We're thinking: 

- Have the option to: 
  - by default, do what it does now; or
  - optionally, render the rest of the document except the parts that cause an exception
- Be able to pass some callback that handles rendering exceptions (e.g. so we can log them/send them to our error reporting service) 
  - perhaps this callback could be how people decide if parts that throw exceptions are just not rendered vs whole document is not rendered

What do you reckon?

**Comment by 0b10** [comment] 2019-09-05 15:59
@SircleCquare  I've just had the same issue with react-syntax-highlighter. The issue is that it expects some defined text, otherwise it throws.  This isn't normally an issue, but I'm building a live preview - so when the user types ```, the syntax highlighter renderer is called, and the text is undefined - so it always throws.

The two approaches I've come up with: an error boundary; a validating wrapper.

I'm just leaving this comment here so that the author can decide if it's something this lib should handle.

**Comment by ChristianMurphy** [comment] 2020-10-08 14:39
To answer the first question about `</br>` crashing this will be resolved in #428.
To answer the question of handling errors, @0b10's suggestion of https://reactjs.org/docs/error-boundaries.html would be a good approach

**Closed** 2020-10-08 15:37 UTC
Labels: 🙋 type/question
