### ISSUE TITLE
How to append content ,not cover?

### ISSUE THREAD

**Issue by finylink** [remarkjs/react-markdown#823] opened 2024-04-01 05:43 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

when using ReactMarkdown, I set the content of<ReactMarkdown>{content}</ReactMarkdown>. My content is a streaming output (using eventstream). When there are images inside, because ReactMarkdown always conver the content, every time the data comes in, the images are rendered multiple times, appearing to blink continuously.
How  to solve this problem?

### Solution

i don't know.

### Alternatives

i don't know

**Comment by remcohaszing** [comment] 2024-04-01 10:05
Please read https://github.com/remarkjs/.github/blob/main/support.md#asking-quality-questions and provide a minimal, runnable reproduction.

This is likely a duplicate of https://github.com/remarkjs/react-markdown/issues/821.

**Closed** 2024-04-01 19:49 UTC
Labels: 🙋 no/question, 👎 phase/no
