### ISSUE TITLE
Using react-markdown with Webpack 5 is not possible as path dependency/polyfill is missing

### ISSUE THREAD

**Issue by ceisele-r** [remarkjs/react-markdown#514] opened 2020-11-25 10:51 UTC
### Subject of the issue

After upgrading a project using `react-markdown` to Webpack 5, webpack compile fails because a polyfill for `path` is missing.
The reason for this is that webpack 5 does [no longer automatically include polyfills for core node modules](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed).

The affected dependency tree results from
```
ERROR in ./node_modules/vfile/core.js 3:11-26
Module not found: Error: Can't resolve 'path' in 'C:\app\node_modules\vfile'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./node_modules/vfile/index.js 5:12-32
 @ ./node_modules/unified/index.js 15:12-28
 @ ./node_modules/react-markdown/lib/react-markdown.js 5:14-32
 @ ./src/vendor.js 164:0-25
 @ dll vendor vendor[0]
```

There is an issue for the underlying issue in vfile where a recent comment references the same issue ( https://github.com/vfile/vfile/issues/16#issuecomment-732674005 ) where it seems that setting up unified to be able to run in browser now with Webpack 5 is not straightforward.

=> As a result it means that `react-markdown` is not able to be used in react projects with webpack 5 easil. Therefore, I'm creating this issue here.
If changing dependencies (to avoid the dependency tree to the `path` dependency) is not an option, I think somewhere in the docs should be documented how to use react-markdown with Webpack 5.

### Your environment

*   **OS**: Windows
*   **Packages**: react-markdown 5.0.2
*   **Env**: Webpack 5.6.0, node 12.19.0

### Steps to reproduce

1. Use existing react project with `webpack` 4 and `react-markdown`
2. Update to webpack 5
3. Compile webpack

### Expected behavior

`react-markdown` is frontend-compatible and works without further modifications to dependencies / webpack polyfills with webpack 5.

### Actual behavior

See above.

**Comment by ChristianMurphy** [comment] 2020-11-25 12:51
Duplicate of https://github.com/vfile/vfile/discussions/57#discussion-27416
You can find resolutions at https://github.com/vfile/vfile/discussions/57#discussioncomment-110084

**Closed by ChristianMurphy** 2020-11-25 12:51 UTC
Labels: 🐛 type/bug, 🔍 status/open

**Comment by evenfrost** [comment] 2020-12-07 17:52
FWIW, fixed with
```
npm i path-browserify
```
and adding to the webpack config:
```js
module.exports = {
    resolve: {
        fallback: { 'path': require.resolve('path-browserify') },
    },
};
```

**Comment by ChristianMurphy** [comment] 2020-12-07 18:10
Also see https://github.com/vfile/vfile/releases/tag/4.2.1 which offers an alternative to polyfilling path https://github.com/vfile/vfile/releases/tag/4.2.1
