### ISSUE TITLE
Can't render a table

### ISSUE THREAD

**Issue by blb78** [remarkjs/react-markdown#529] opened 2021-01-14 16:30 UTC
### Can't render a table with gfm plugin
Hi ! 
I see that your demo's page can't render it too [see the table section](https://remarkjs.github.io/react-markdown/)

Maybe if you know why your demo is buggy it can help me. Because I can't reproduce on a fresh install.
And I don't why I can't render table...
I post this report on this repo because I see in your demo's page the bug. 
My bad if you think this is not the right place.

### Your environment
*   **OS**: Win10 pro
*   **Packages**:
    -  react-dom : 17.0.1
    -  react : 17.0.1
    -  react-markdown : 5.0.3
    -  remark-gfm : 1.0.0
*   **Env**:
    - nodejs : 14.15.1
    - npm : 6.14.8
    - firefox : 84.0.2

### Steps to reproduce
I can't reproduce !

On a fresh install it works

- npx create-react-app my-app --template typescript
- yarn add react-markdown
- yarn add remark-gfm

### Expected behavior
See a html table

### Actual behavior

See a inline markdown table, like your demo

**Comment by ChristianMurphy** [comment] 2021-01-14 16:37
duplicate of https://github.com/remarkjs/react-markdown/issues/526, https://github.com/remarkjs/react-markdown/issues/525, https://github.com/remarkjs/react-markdown/issues/524, https://github.com/remarkjs/react-markdown/issues/516, and https://github.com/remarkjs/react-markdown/issues/493

how to use tables (and the rest of GitHub Flavored Markdown) is documented in the readme https://github.com/remarkjs/react-markdown#use
As for the demo site, it does not include `remark-gfm` and therefore doesn't render tables.

**Closed by ChristianMurphy** 2021-01-14 16:37 UTC
Labels: 🐛 type/bug, 🔍 status/open
