### ISSUE TITLE
tables don't render

### ISSUE THREAD

**Issue by x00F** [remarkjs/react-markdown#516] opened 2020-12-01 01:04 UTC
### Subject of the issue

tables don't work, also does not render in the examples page in my browser. 

### Your environment
chrome on osx - "react-markdown": "^5.0.3"

**Comment by ChristianMurphy** [comment] 2020-12-01 01:12
duplicate of https://github.com/remarkjs/react-markdown/issues/493

**Closed by ChristianMurphy** 2020-12-01 01:12 UTC
Labels: 🐛 type/bug, 🔍 status/open
