### ISSUE TITLE
use plugin rehype-highlight v7.0.0 memory leak

### ISSUE THREAD

**Issue by zzzgydi** [remarkjs/react-markdown#791] opened 2023-11-07 06:55 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-highlight v7.0.0

### Link to runnable example

https://github.com/zzzgydi/rhv7-memory-leak-test

### Steps to reproduce

- `pnpm i`
- `pnpm dev`
- Visit `http://localhost:5173`
- Open Chrome's task manager and find the corresponding tab to observe the memory situation
- Click `start` button
- observe the memory situation
- Click `stop` and `clear` button and observe

#### As a comparison
- Change `rehype-highlight v7.0.0` to `rehype-highlight v6.0.0` in `package.json`
- Repeat the steps above

### Expected behavior

same as `rehype-highlight v6.0.0`

### Actual behavior

<img width="826" alt="image" src="https://github.com/remarkjs/react-markdown/assets/27361820/b54fb249-4095-4668-8951-d750921c7596">

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

Vite

**Comment by immccn123** [comment] 2023-11-08 03:51
can reproduce in <https://remarkjs.github.io/react-markdown/>

![](https://github.com/remarkjs/react-markdown/assets/41335471/edc7281a-4b2c-44f0-afe6-1ae16020090c)

**Comment by ChristianMurphy** [comment] 2024-01-02 19:06
Thanks @zzzgydi and @immccn123!
Memory should not be ballooning in that way.
Would either of you be interested in tracing this further and potentially opening a PR? https://developer.chrome.com/docs/devtools/memory-problems

**Comment by wooorm** [comment] 2024-01-05 11:46
I’m pretty sure V8 and friends actually use up as much memory as they can before freeing it? Maybe you’re seeing memory being used?

**Comment by zzzgydi** [comment] 2024-01-05 14:48
I guess that `lowlight` has registered languages internally, but did not unregisterLanguage. After creating multiple instances like this may cause memory leaks.

Below I have written three comparative examples. In my understanding, if there is no memory leak, the memory should be released after 100 iterations of the for loop.

```typescript
import { createLowlight, common } from "lowlight"; // version: ^3.1.0
import HighlightJs from "highlight.js"; // version: ^11.9.0
import "./App.css";

function customCreateLowlight(grammars: typeof common) {
  const high = HighlightJs.newInstance();
  if (grammars) {
    Object.keys(grammars).forEach((name) =>
      high.registerLanguage(name, grammars[name])
    );
  }
  return high;
}

function App() {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
      <button
        type="button"
        onClick={() => {
          for (let i = 0; i < 100; i++) {
            const lowlight = createLowlight(common);
          }
        }}
      >
        createLowlight
      </button>

      <button
        type="button"
        onClick={() => {
          for (let i = 0; i < 100; i++) {
            const lowlight = customCreateLowlight(common);
          }
        }}
      >
        customCreateLowlight
      </button>

      <div>
        <button
          type="button"
          onClick={() => {
            for (let i = 0; i < 100; i++) {
              const lowlight = customCreateLowlight(common);
              Object.keys(common).forEach((name) =>
                lowlight.unregisterLanguage(name)
              );
            }
          }}
        >
          customCreateLowlight & unregisterLanguage
        </button>
      </div>
    </div>
  );
}
export default App;
```

I obtained the following results. The results are divided into three rounds. First, I refresh the page, recorded, and then click on the button to run once, and recorded next.

<img width="899" alt="image" src="https://github.com/remarkjs/react-markdown/assets/27361820/df276396-a692-494b-a499-f298abd2a745">

<img width="813" alt="image" src="https://github.com/remarkjs/react-markdown/assets/27361820/ca3dd56d-ec21-4316-94bd-bd3dc2b72201">

Through the above graph, it is a comparison of the results between snapshot 6 and snapshot 5. The largest occupation is string type, and these values are related to language settings within highlightjs.

**Comment by wooorm** [comment] 2024-01-09 16:10
> After creating multiple instances like this may cause memory leaks.

If there is indeed a memory leak instead of chrome using up the memory it can use up, then that seems like a highlightjs issue

**Comment by TonyL1u** [comment] 2024-01-10 14:12
I met the same problem, v7 did not work well when v6 was ok.
Is there any resolutions for this problem?

**Comment by wooorm** [comment] 2024-01-10 14:18
The solution is you can contribute to open source and figure out a solution instead of spamming duplicate info.

**Comment by TonyL1u** [comment] 2024-01-10 14:25
> The solution is you can contribute to open source and figure out a solution instead of spamming duplicate info.

good advice

**Comment by alielmorsy** [comment] 2024-02-08 06:13
Did anyone find a solution for that?
I am using that code and yes  there is a weird memory leak because it renders code blocks over and over:
```
   <Markdown rehypePlugins={[rehypeRaw, rehypeHighlight]} components={{
                code({node, className, children, ...props}) {
                    return <div className={className}>
                        {children}
                    </div>
                },
            }}>
                {post.content}
            </Markdown>
```

**Comment by remcohaszing** [comment] 2024-02-08 08:26
If possible, you should provide components with a stable identity to avoid rerenders.

```jsx
function Code({ node, className, children, ...props }) {
  return (
    <div className={className}>
      {children}
    </div>
  )
}

export function Post({ post }) {
  return (
    <Markdown
      rehypePlugins={[rehypeRaw, rehypeHighlight]}
      components={{code: Code}}
    >
      {post.content}
    </Markdown>
  )
}
```

Also, if possible, you should provide props with a stable identity to reduce rerenders even further.


```jsx
function Code({node, className, children, ...props}) {
  return (
    <div className={className}>
      {children}
    </div>
  )
}

const components = {
  code: Code
}

const rehypePlugins = [
  rehypeRaw,
  rehypeHighlight
]

export function Post({ post }) {
  return (
    <Markdown
      rehypePlugins={rehypePlugins}
      components={components}
    >
      {post.content}
    </Markdown>
  )
}
```

**Comment by aeharding** [comment] 2024-05-03 17:07
This memory leak appears to happen by simply including rehype-remark, even without any actual highlighted content.

> If possible, you should provide components with a stable identity to avoid rerenders.

This does not noticeably address the leak in my testing

As others suggest, my current workaround is to use v6.

**Comment by immccn123** [comment] 2024-08-01 02:02
This issue seems to be caused by the `DOMContentLoaded` event listener on the window not being removed in a timely manner. You can type anything on https://remarkjs.github.io/react-markdown/ and use `getEventListeners(window).DOMContentLoaded` in a Chromium-based browser to compare the length before and after.

https://github.com/user-attachments/assets/eae3e07b-3852-49d2-84eb-7c434ff55c25

**Comment by wooorm** [comment] 2024-08-01 07:27
Thanks for investigating this and looking for a proper fix, Imken!

**Comment by wooorm** [comment] 2024-09-17 11:53
Thanks again, closed in https://github.com/highlightjs/highlight.js/pull/4095!

**Closed by wooorm** 2024-09-17 11:53 UTC
Labels: 🤞 phase/open
